config/routes.rb
AdmiosDeck::Application.routes.draw do
  

  root  'static_pages#home'
  post "user_destroy" => "users#destroy", :as => "user_destroy"
  get "delete_account" => "users#delete", :as => "delete_account"
  get "dashboard" => "static_pages#dashboard", :as => "dashboard"
  get "twitter_list" => "static_pages#twitter_list", :as => "twitter_list"
  get "manage_user" => "users#manage_user", :as => "manage_user"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  resources :twitter_accounts

  

end

app/models/twitter_account.rb
class TwitterAccount < ActiveRecord::Base
	belongs_to :user

	attr_accessible :username

	validates_presence_of :username
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :twitter_accounts, :dependent => :destroy

  authenticates_with_sorcery!

  attr_accessible :username, :password, :password_confirmation
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username
  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_authenticated
    redirect_to login_url, :alert => "First login to access this page."
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = login(params[:username], params[:password], params[:remember_me])
    if user
      redirect_back_or_to dashboard_path, :notice => "Logged in!"
    else
      flash.now.alert = "Username or password was invalid"
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/static_pages_controller.rb
require 'tweetstream'

class StaticPagesController < ApplicationController
  before_filter :require_login, :only => [:dashboard, :twitter_list]
  
  def home
  end

  def dashboard
  end

  def twitter_list
   @twitter_accounts = current_user.twitter_accounts
  end

end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
  before_action :set_twitter_account, only: [:show, :edit, :update, :destroy]
  before_filter :require_login

  def new
    @twitter_account = TwitterAccount.new
  end

  def edit
  end

  def create
    @twitter_account = TwitterAccount.new(params[:twitter_account])
    @twitter_account.user_id =current_user.id
    if @twitter_account.save
      redirect_to twitter_list_path, notice: 'Twitter account was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @twitter_account.update(params[:twitter_account])
      redirect_to twitter_list_path, notice: 'Twitter account was successfully updated.'
    end
  end

  def destroy
    @twitter_account.destroy
    redirect_to twitter_list_path
  end

  private

    def set_twitter_account
      @twitter_account = TwitterAccount.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :require_login, :only => :delete

	def new
	  @user = User.new
	end

	def create
	  @user = User.new(params[:user])
	  if @user.save
	    redirect_to root_path, :notice => "Signed up!"
	  else
	    render :new
	  end
	end

	def destroy
	  if !User.authenticate(current_user.username, params[:password]).nil?
	    current_user.destroy
        redirect_to login_url, :alert => "Your account has been deleted."
      else
      	redirect_to delete_account_path, :alert => "Incorrect password."
  	  end
    end

	def manage_user
	end

	def delete
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/twitter_accounts_helper.rb
module TwitterAccountsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdmiosDeck</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script src="http://js.pusher.com/2.1/pusher.min.js" type="text/javascript"></script>
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">      
        <% if current_user %>
          <ul class="nav navbar-nav">
            <li class="item-1"><%= link_to "Dashboard", dashboard_path %></li>
            <li class="item-2"><%= link_to "Manage Account", manage_user_path %></li>
          </ul>
          <ul class="nav pull-right">
            <li><%= link_to "Log out", logout_path %></li>
          </ul>
          <p class="navbar-text pull-right">Logged in as <%= current_user.username %>.</p>
        <% else %>
          <ul class="nav navbar-nav">
            <li><%= link_to "Sign up", signup_path %></li>
            <li><%= link_to "log in", login_path %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
  <br/>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/static_pages/dashboard.html.erb
    <script type="text/javascript">
    $(document).ready(function(){
      if(typeof pusher === 'undefined'){
        pusher = new Pusher('98d1cd189b6bdb479506');
        var channel = pusher.subscribe('<%= current_user.username %>');
        channel.bind('new_tweet', function(data) {
          $("#feed").prepend("<div id=\"item\" class=\"well well-large\">" + data.message + "</div>");
        });
      };
    }); 
    </script>
    <div id="feed">

app/views/static_pages/home.html.erb
<h1>Welcome to the AdmiosDeck WebApp</h1>
<p></p>

app/views/static_pages/twitter_list.html.erb
<h1>Your Twitter accounts</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @twitter_accounts.each do |twitter_account| %>
    <tr>
      <td class="separate"><%= twitter_account.username %></td>
      <td>
        <div class="btn-group">
          <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
            Actions
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Edit', edit_twitter_account_path(twitter_account) %></li>
            <li><%= link_to 'Delete', twitter_account, method: :delete%></li>
          </ul>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<button class="btn"><%= link_to 'New Twitter account', new_twitter_account_path %></button>

app/views/twitter_accounts/_form.html.erb
<%= form_for(@twitter_account) do |f| %>
  <% if @twitter_account.errors.any? %>
    <div class="alert alert-error">
      <ul>
      <% @twitter_account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/twitter_accounts/edit.html.erb
<h1>Editing Twitter account</h1>

<%= render 'form' %>

<button class="btn"><%= link_to 'Back', twitter_accounts_path %></button>

app/views/twitter_accounts/new.html.erb
<h1>Add Twitter account to your list</h1>

<%= render 'form' %>

<button class="btn"><%= link_to 'Back', twitter_accounts_path %></button>

app/views/users/delete.html.erb
<%= form_tag({:controller => 'users', :action => 'destroy'}) do %>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-error" %>
  <% end %>

  <div class="field">
    <%= label_tag "Current password:" %>
    <%= password_field_tag :password %>
  </div>
  <div class="actions"><%= submit_tag "Delete" %></div>
<% end %>

app/views/users/manage_user.html.erb
<div class="row">  
  <div class="span6">  
    <ul class="nav nav-tabs nav-stacked">  
      <li class="nav-header">Manage your Account</li>
      <li><%= link_to "Your Twitter Accounts", twitter_list_path %></li>
      <li><%= link_to "Delete account", delete_account_path %></li>
    </ul>
  </div>
</div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div  class="alert alert-error">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>